Resources:
  codeBucket:
    Type: 'AWS::S3::Bucket'
Outputs:
  s3Bucket:
    Description: 'The bucket to store lambdafunction code in'
    Value: !Ref codeBucket
    Export:
      Name: !Sub "${AWS::StackName}-s3Bucket"